import path from "path";
import { fileURLToPath } from "url";
import { IgBot } from "../core/IgBot.js";
import { CommandLineUI, UserInputAsListOptions } from "../cli/CommandLine.js";

// Bot menu options
import followUser from "../logic/followUser.js";
import unfollowUser from "../logic/unfollowUser.js";
import getFollowersList from "../logic/getFollowersList.js";
import getFollowingList from "../logic/getFollowingList.js";
import getUserWhoDontFollowBack from "../logic/getUsersWhoDontFollowBack.js";
import unfollowUsersWhoDontFollowBack from "../logic/unfollowUsersWhoDontFollowBack.js";

// Loading __dirname
const __dirname = path.dirname(fileURLToPath(import.meta.url));

// Path to store files generated by the bot
const BOT_DATA_BASE_PATH = `${__dirname}/../../bot_data`;

// Enum to store bot menu choices to further check it
enum botMenuListChoices {
    UNFOLLOW_USER,
    UNFOLLOW_USERS_WHO_DONT_FOLLOW_BACK,

    FOLLOW_USER,

    GET_FOLLOWING_LIST,
    GET_FOLLOWERS_LIST,
    GET_LIST_OF_USERS_WHO_DONT_FOLLOW_BACK,

    EXIT_BOT_MENU,
}

const botMenuListOptions: UserInputAsListOptions = {
    title: "Bot Menu",
    choices: [
        {
            name: "Follow A User \u2795",
            out: botMenuListChoices.FOLLOW_USER,
        },
        {
            name: "Unfollow A User \u2796",
            out: botMenuListChoices.UNFOLLOW_USER,
        },
        {
            name: "Unfollow Users Who Don't Follow Back 🔙",
            out: botMenuListChoices.UNFOLLOW_USERS_WHO_DONT_FOLLOW_BACK,
        },
        {
            name: "Get the list of following users 📃",
            out: botMenuListChoices.GET_FOLLOWING_LIST,
        },
        {
            name: "Get the list of followers 📃",
            out: botMenuListChoices.GET_FOLLOWERS_LIST,
        },
        {
            name: "Get the list of users who don't follow back 📃",
            out: botMenuListChoices.GET_LIST_OF_USERS_WHO_DONT_FOLLOW_BACK,
        },
        {
            name: "Exit Bot Menu ❌",
            out: botMenuListChoices.EXIT_BOT_MENU,
        },
    ],
};

export async function displayBotMenu(
    bot: IgBot,
    logger: { getLogger(): any; allowLogging: boolean },
): Promise<boolean | false> {
    const botMenuInput: botMenuListChoices =
        await CommandLineUI.getUserInputFromList(botMenuListOptions);

    switch (botMenuInput) {
        case botMenuListChoices.FOLLOW_USER: // Done
            await followUser(bot, logger.allowLogging);
            break;
        case botMenuListChoices.UNFOLLOW_USER: // Done
            await unfollowUser(bot, logger.allowLogging);
            break;
        case botMenuListChoices.UNFOLLOW_USERS_WHO_DONT_FOLLOW_BACK: // Done
            await unfollowUsersWhoDontFollowBack(
                bot,
                logger.allowLogging,
                BOT_DATA_BASE_PATH,
            );
            break;
        case botMenuListChoices.GET_FOLLOWING_LIST: // Done
            await getFollowingList(
                bot,
                logger.allowLogging,
                BOT_DATA_BASE_PATH,
            );
            break;
        case botMenuListChoices.GET_FOLLOWERS_LIST:
            await getFollowersList(
                bot,
                logger.allowLogging,
                BOT_DATA_BASE_PATH,
            );
            break;
        case botMenuListChoices.GET_LIST_OF_USERS_WHO_DONT_FOLLOW_BACK: // Done
            await getUserWhoDontFollowBack(
                bot,
                logger.allowLogging,
                BOT_DATA_BASE_PATH,
            );
            break;
        case botMenuListChoices.EXIT_BOT_MENU: // Done
            return false;
    }
}
